cendari/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import RedirectView
from editorsnotes.main.views.auth import CustomBrowserIDVerify

from editorsnotes.main.views.topics import LegacyTopicRedirectView

from editorsnotes.admin.views.notes import NoteAdminView
#from editorsnotes.api.views.notes import NoteList


from cendari.views import NoteCendari,DocumentCendari, EditNoteAdminView, EditDocumentAdminView, EditTopicAdminView,  EditTranscriptAdminView
import cendari.views
import editorsnotes.admin.views
#admin.autodiscover()

# These will be intercepted by apache in production
urlpatterns = patterns('',
    (r'^favicon.ico$', RedirectView.as_view(url='/static/style/icons/favicon.ico')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT }),
    (r'^proxy$', 'editorsnotes.main.views.proxy'),
)


# Auth patterns
urlpatterns += patterns('',
    url(r'^accounts/login/$', 'cendari.views.user_login', name='user_login_view'),
    url(r'^accounts/logout/$', 'cendari.views.user_logout', name='user_logout_view'),
    url(r'^accounts/profile/$', 'editorsnotes.main.views.auth.user'),
    url(r'^accounts/profile/feedback/$', 'editorsnotes.main.views.auth.user_feedback', name='user_feedback_view'),
    url(r'^accounts/browserid/$', CustomBrowserIDVerify.as_view(), name='browserid_verify'),
    url(r'^user/(?P<username>[\w@\+\.\-]+)/$', 'editorsnotes.main.views.auth.user', name='user_view'),
)

#
# django-admin2 patterns
# 

USE_ADMIN2 = False
try:
    import djadmin2
    USE_ADMIN2 = True
except:
    pass

if USE_ADMIN2:
    import admin2
    urlpatterns += patterns('',
                            url(r'^admin2/', include(djadmin2.default.urls)))

# Base patterns
urlpatterns += patterns('editorsnotes.main.views.navigation',
    #url(r'^$', 'index', name='index_view'),
    url(r'^about/$', 'about', name='about_view'),
    url(r'^about/test/$', 'about_test'),
#    url(r'^search/$', 'search', name='search_view'),
    url(r'^version/$', 'get_version', name='get_version'),
)

# Admin patterns
urlpatterns += patterns('',
    url(r'^projects/(?P<project_slug>[-\w]+)/', include('editorsnotes.admin.urls', namespace='admin', app_name='admin')),
    url(r'^projects/add/', 'editorsnotes.admin.views.projects.add_project', name='add_project_view'),
)

# Main model patterns
urlpatterns += patterns('',
    url(r'^', include('editorsnotes.main.urls')),
)

# API
urlpatterns += patterns('',
    url(r'^api/', include('editorsnotes.api.urls', namespace='api', app_name='api')),
    url(r'^api/metadata/topics/types/$', 'editorsnotes.api.views.topics.topic_types'),
)

urlpatterns += patterns('editorsnotes.djotero.views',
#    url(r'^document/upload/$', 'import_zotero', name='import_zotero_view'),
#    url(r'^document/upload/libraries/$', 'libraries', name='libraries_view'),
#    url(r'^document/upload/collections/$', 'collections', name='collections_view'),
#    url(r'^document/upload/items/$', 'items', name='items_view'),
#    url(r'^document/upload/continue/$', 'items_continue', name='items_continue_view'),
#    url(r'^document/upload/import/$', 'import_items', name='import_items_view'),
    url(r'^user/zotero_info$', 'update_zotero_info', name='update_zotero_info_view'),
    url(r'^api/metadata/documents/item_template/$', 'item_template', name='item_template_view'),
    url(r'^api/metadata/documents/item_types/$', 'item_types', name='item_types_view'),
    url(r'^api/metadata/documents/item_type_creators/$', 'item_type_creators', name='item_type_creators_view'),
    url(r'^api/document/archives/$', 'api_archives', name='api_archives_view'),
)
urlpatterns += patterns('editorsnotes.refine.views',
   url(r'^cendari/(?P<project_slug>[-\w]+)/topics/clusters/$', 'show_topic_clusters', name='show_topic_clusters_view'),
   url(r'^cendari/topics/merge/(?P<cluster_id>\d+)/$', 'merge_topic_cluster', name='merge_topic_cluster_view'),
)

import editorsnotes.admin.views.projects

cendaripatterns = patterns('cendari.views',
    url(r'^$','index', name='index_view'),
    url(r'^browse/$', 'browse_cendari', name='cendari_browse_view'),
    url(r'^cendari/browse/$', 'browse_cendari', name='cendari_browse_view'),
    url(r'^about/$', 'about_cendari', name='cendari_about_view'),
    url(r'^cendari/about/$', 'about_cendari', name='cendari_about_view'),
    url(r'^cendari/external/(?P<type>\w+)/$', 'iframe_view', name='iframe_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/index$', 'index', name='index_project'),
    

    # Cendari Projects
    url(r'^cendari/projects/add/',                                                          'cendari_project_add',                name='add_project_view'),
    url(r'^cendari/projects/(?P<project_id>\d+)/$',                                          'cendari_project_change',            name='project_view'),
    url(r'^cendari/projects/(?P<project_slug>[-\w]+)/view/$',                                          'cendari_project_view',            name='project_read_view'),
    url(r'^cendari/projects/(?P<project_id>\d+)/add_alias/$',                                          'add_project_slug',            name='add_project_slug_view'),
    url(r'^projects/(?P<project_slug>[-\w]+)/',                                                 include('editorsnotes.admin.urls',   namespace='admin', app_name='admin')),
    #url(r'^cendari/projects/add/$',                                                         cendari.views.change_project,        name='addproject_view'),
    #url(r'^cendari/projects/(?P<slug>[-_a-z0-9]+)/$',                                       EditProjectAdminView.as_view(),      name='project_view'),

	# Cendari Notes
    #url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$',                          EditNoteAdminView.as_view(),         name='note_view'),
   # url(r'^cendari/(?P<project_slug>[-\w]+)/notes/add/$',                                       EditNoteAdminView.as_view(),         name='addnote_view'),
    #url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$',                          NoteCendari.as_view(),                    name='note_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/add/$',                                       NoteCendari.as_view(),                name='addnote_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/edit/$',                          'editNoteCendari',                name='note_edit'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/read/$',                          'readNoteCendari',                name='note_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$',                          'readNoteCendari',                name='note_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/version_history$',                          'versionHistoryNoteCendari',                name='note_version_history'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/version_history/(?P<version_id>\d+)$',  'versionNoteCendari',                name='note_version'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/rdfa/$', 'rdfa_view_note', name='rdfa_view_note'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/download/$', 'rdfa_download_note', name='rdfa_download_note'),

    # Cendari Documents
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/transcript/$',       EditTranscriptAdminView.as_view(),   name='transcript_edit_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/rdfa/$', 'rdfa_view_document', name='rdfa_view_document'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/download/$', 'rdfa_download_document', name='rdfa_download_document'),
   # url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/$',                  EditDocumentAdminView.as_view(),     name='document_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/edit/$',                 'editDocumentCendari',                name='document_edit'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/read/$',                 'readDocumentCendari',                name='document_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/$',                 'readDocumentCendari',                name='document_read'),
   # url(r'^cendari/(?P<project_slug>[-\w]+)/documents/add/$',                                   EditDocumentAdminView.as_view(),     name='adddocument_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/add/$',                                   DocumentCendari.as_view(),     name='adddocument_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/document/(?P<document_id>\d+)/version_history$',                          'versionHistoryDocumentCendari',                name='document_version_history'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/version_history/(?P<version_id>\d+)$',  'versionDocumentCendari',                name='document_version'),
    # Cendari Topics
    #url(r'^cendari/(?P<project_slug>[-\w]+)/topics/add/$',                                      EditTopicAdminView.as_view(),        name='addtopic_view'),
    #url(r'^cendari/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/$',                   EditTopicAdminView.as_view(),        name='topic_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/$',                   'readEntityCendari',                  name='topic_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/edit$',                   'editEntityCendari',                  name='topic_edit'),

editorsnotes/admin/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^edit/$', views.projects.change_project, name='main_project_change'),
    url(r'^roster/$', views.projects.project_roster, name='main_project_roster_change'),
    url(r'^roles/$', views.projects.change_project_roles, name='main_project_roles_change'),
    url(r'^featured_items/$', views.projects.change_featured_items, name='main_featured_items_change'),
    url(r'^topics/add/$', views.topics.TopicAdminView.as_view(), name='main_topic_add'),
    url(r'^topics/(?P<topic_node_id>\d+)/edit/$', views.topics.TopicAdminView.as_view(), name='main_topic_change'),
    url(r'^documents/add/$', views.documents.DocumentAdminView.as_view(), name='main_document_add'),
    url(r'^documents/(?P<document_id>\d+)/edit/$', views.documents.DocumentAdminView.as_view(), name='main_document_change'),
    url(r'^documents/(?P<document_id>\d+)/transcript/edit/$', views.documents.TranscriptAdminView.as_view(), name='main_transcript_add_or_change'),
    url(r'^notes/add/$', views.notes.NoteAdminView.as_view(), name='main_note_add'),
    url(r'^notes/(?P<note_id>\d+)/edit/$', views.notes.NoteAdminView.as_view(), name='main_note_change'),
)

editorsnotes/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url, include
from django.conf import settings
from django.views.generic.base import RedirectView
from editorsnotes.main.views.auth import CustomBrowserIDVerify

# These will be intercepted by apache in production
urlpatterns = patterns('',
    (r'^favicon.ico$', RedirectView.as_view(url='/static/style/icons/favicon.ico')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT }),
    (r'^proxy$', 'editorsnotes.main.views.proxy'),
)

# Auth patterns
urlpatterns += patterns('',
  # CENDARI:old  url(r'^accounts/login/$', 'django.contrib.auth.views.login', { 'redirect_field_name': 'return_to' }),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', { 'redirect_field_name': 'return_to' }, name='user_login_view'),
    url(r'^accounts/logout/$', 'editorsnotes.main.views.auth.user_logout', name='user_logout_view'),
    url(r'^accounts/profile/$', 'editorsnotes.main.views.auth.user'),
    url(r'^accounts/profile/feedback/$', 'editorsnotes.main.views.auth.user_feedback', name='user_feedback_view'),
    url(r'^accounts/browserid/$', CustomBrowserIDVerify.as_view(), name='browserid_verify'),
    url(r'^user/(?P<username>[\w@\+\.\-]+)/$', 'editorsnotes.main.views.auth.user', name='user_view'),
)

# Base patterns
urlpatterns += patterns('editorsnotes.main.views.navigation',
#    url(r'^$', 'index', name='index_view'),
#    url(r'^about/$', 'about', name='about_view'),
#    url(r'^about/test/$', 'about_test'),
#    url(r'^search/$', 'search', name='search_view'),
    url(r'^version/$', 'get_version', name='get_version'),
)

# Admin patterns
urlpatterns += patterns('',
    url(r'^projects/(?P<project_slug>\w+)/', include('editorsnotes.admin.urls', namespace='admin', app_name='admin')),
    url(r'^projects/add/', 'editorsnotes.admin.views.projects.add_project', name='add_project_view'),
)

# Main model patterns
urlpatterns += patterns('',
    url(r'^', include('editorsnotes.main.urls')),
)

# API
urlpatterns += patterns('',
    url(r'^api/', include('editorsnotes.api.urls', namespace='api', app_name='api')),
    url(r'^api/metadata/topics/types/$', 'editorsnotes.api.views.topics.topic_types'),
)


urlpatterns += patterns('editorsnotes.djotero.views',
#    url(r'^document/upload/$', 'import_zotero', name='import_zotero_view'),
#    url(r'^document/upload/libraries/$', 'libraries', name='libraries_view'),
#    url(r'^document/upload/collections/$', 'collections', name='collections_view'),
#    url(r'^document/upload/items/$', 'items', name='items_view'),
#    url(r'^document/upload/continue/$', 'items_continue', name='items_continue_view'),
#    url(r'^document/upload/import/$', 'import_items', name='import_items_view'),
    url(r'^user/zotero_info$', 'update_zotero_info', name='update_zotero_info_view'),
    url(r'^api/metadata/documents/item_template/$', 'item_template', name='item_template_view'),
    url(r'^api/metadata/documents/item_types/$', 'item_types', name='item_types_view'),
    url(r'^api/metadata/documents/item_type_creators/$', 'item_type_creators', name='item_type_creators_view'),
    url(r'^api/document/archives/$', 'api_archives', name='api_archives_view'),
   # CENDARI:old url(r'^api/document/template/', 'zotero_template'),
   # CENDARI:old url(r'^api/document/blank/$', 'get_blank_item', name='get_blank_item_view'),
   # CENDARI:old url(r'^api/document/itemtypes/$', 'get_item_types'),
   # CENDARI:old url(r'^api/document/csl/$', 'zotero_json_to_csl', name='zotero_json_to_csl_view'),
   # CENDARI:old url(r'^api/document/archives/$', 'api_archives', name='api_archives_view'),
)
#urlpatterns += patterns('editorsnotes.refine.views',
#    url(r'^topics/clusters/$', 'show_topic_clusters', name='show_topic_clusters_view'),
#    url(r'^topics/merge/(?P<cluster_id>\d+)/$', 'merge_topic_cluster', name='merge_topic_cluster_view'),
#)

editorsnotes/admin/templates/admin_base.html
{% extends "base.html" %}

{% load display staticfiles %}

{% block js %}
  <script src="{% static "function/zotero.jquery.js" %}"></script>
  <script src="{% static "function/admin-bootstrap-base.js" %}"></script>
  {% if form.media %}{{ form.media.js }}{% endif %}
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static "style/bootstrap-admin.css" %}" type="text/css" />
  {% if form.media %}{{ form.media.css }}{% endif %}
{% endblock %}

{% block content %}
  {% block page_title %}
  <h2>{% if form.instance.id %}Change{% else %}Add{% endif %} {{ form.Meta.model|object_name|lower }}</h2>
  {% endblock %}

  {% block admin %}
  {% endblock %}

{% endblock %}

editorsnotes/admin/templates/backbone_bootstrap.html
{% extends "base.html" %}

{% block js %}
<script type="text/javascript">
EditorsNotes.bootstrap = {{ bootstrap|safe }};
</script>
{% endblock %}

editorsnotes/admin/templates/featured_items_admin.html
{% extends "base.html" %}

{% load display %}

{% block js %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#autocomplete-type').change(function() {
      var autocompleteModel = this.value,
        $autocompleteField = $(this).siblings('input.search-autocomplete');
      $autocompleteField.attr('search-target', autocompleteModel);
    }).trigger('change');

  });
</script>
{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}

  <h3>Featured items:</h3>
  {% for item in featured_items %}
  <label class="checkbox">
    <input type="checkbox"
           name="delete-item"
           value="{{ item.id }}" />{{ item.content_object|as_link }}
  </label>
  {% endfor %}
  <span class="quiet">Check items to delete.</span>

  <hr/>

  {% if featured_items.count < 5 %}
  <h5>Add an item</h5>
  <select id="autocomplete-type" class="span2">
    <option value="notes">Note</option>
    <option value="documents">Document</option>
    <option value="topics">Topic</option>
  </select>
  <input type="text" placeholder="Type to search" data-project-slug={{ project.slug }} class="span5 search-autocomplete autocomplete-no-redirect"></input>
  {% else %}
    <p>You can only designate up to five featured items. Remove at least one item to add another.</p>
  {% endif %}

  <div>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>

  </form>



{% endblock %}

editorsnotes/admin/templates/project_change.html
{% extends "base.html" %}

{% block content %}
<form enctype="multipart/form-data" method="post">{% csrf_token %}
  {{ form.as_p }}
  <input class="btn" type="submit" value="Save">
</form>
{% endblock %}

editorsnotes/admin/templates/project_roles.html
{% extends "base.html" %}

{% block js %}
<script type="text/javascript">
(function () {

  function addFormToTable($el, $table) {
    var $input = $el.find('input[type="text"]')
      , $checkboxes = $el.find('input[type="checkbox"][name*="permissions"]')
      , $deleteBox = $el.find('input[name*="DELETE"]')
      , $rows = $table.find('tbody tr')
      , $header
      , $footer

    $header = $('<th>')
      .append($input.hide())
      .append($input.val())
      .appendTo( $table.find('thead tr') )

    if ( $input.val() == 'Editor' ) {
      $header.addClass('editor-role');
    }

    $footer = $header.clone().appendTo( $table.find('tfoot tr') );

    $footer.find('input').remove();

    $('tfoot th:last:not(.editor-role)')
      .append('<button class="btn btn-danger" type="button">Delete</button>')
      .find('button')
      .css({
        'display': 'block',
        'position': 'relative',
        'margin': '16px auto -44px'
      })
      .on('click', function () {
        var $tds = $checkboxes.closest('td').add($footer).add($header);

        if ($deleteBox.prop('checked')) {
          $tds.removeClass('to-delete');
          $deleteBox.prop('checked', false)
          $(this).text('Delete');
        } else {
          $tds.addClass('to-delete');
          $deleteBox.prop('checked', true)
          $(this).text('Undo');
        }
      })


    $checkboxes.each(function (idx, el) { 
      $('<td>').append(el).appendTo( $rows.eq(idx) );
    });

  }

  $(document).ready(function () {
    var $table = $('table')

    $('.permission-form').each(function (idx, el) {
      addFormToTable($(el), $table);
    });

    $('<button class="btn btn-primary">Add role</button>')
      .appendTo('body')
      .css({ 'padding': '7px 16px', 'width': '100px' })
      .position({
        'my': 'left+12 top+12',
        'at': 'right',
        'of': $table.find('thead')
      })
      .on('click', function () {
        $(this).remove();
        $table.find('th:last-of-type, th:last-of-type input, td:last-of-type').show();
      });

  });
  
})()
</script>
{% endblock %}

{% block css %}
<style type="text/css">
  #perms-table {
    width: auto;
  }
  td:first-of-type {
    width: 180px;
  }
  td:not(:first-of-type), th:not(:first-of-type) {
    text-align: center;
    min-width: 100px;
  }
  th input[type="text"] {
    margin: 0;
    text-align: center;
  }
  #perms-table tr:hover td {
    background: #fffacd;
  }
  #perms-table th {
    vertical-align: middle;
  }
  .hide-extra td:last-of-type, .hide-extra th:last-of-type {
    display: none;
  }

  td.to-delete, th.to-delete {
    background: #fa8072 !important;
  }
</style>
{% endblock %}

{% block content %}

<h1>Change project roles</h1>
{% include "includes/bootstrap_errors.html" with errors=formset.errors %}
<form method="post">
  {% csrf_token %}
  <table id="perms-table" class="table table-condensed table-bordered table-striped hide-extra">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for perm in formset.all_perms %}
      <tr>
        <td>{{ perm.name }}</td>
      </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr>
        <th></th>
      </tr>
    </tfoot>
  </table>
  <div style="display: none;">
    {{ formset.management_form }}
    {% for form in formset.forms %}
    <div class="permission-form">{{ form }}</div>
    {% endfor %}
  </div>
  <button type="submit" class="btn">Save roles</button>
</form>

{% endblock %}

editorsnotes/admin/templates/project_roster.html
{% extends "base.html" %}

{% block css %}
<style type="text/css">
  td { vertical-align: middle !important; }
  table select { margin-bottom: 0px; }
  .project-invitations select,
  .project-invitations input {
    margin-bottom: 0px;
  }
  .project-invitations div {
    margin-bottom: .75em;
  }
  .remove-project-invitation {
    position: relative;
    left: 2px;
    top: 1px;
  }
  .remove-project-invitation:not(:hover) {
    color: black;
  }
  .remove-project-invitation:hover {
    text-decoration: none;
  }
</style>
{% endblock %}

{% block js %}
{% if roster_formset %}
<script type="text/javascript">
  $(document).ready(function () {
    $('.project-user-form').each(function () {
      var $this = $(this)
        , thisId = $this.find('input[name$="id"]').val()

      if (thisId == {{ request.user.id }}) { return; }

      $('.project-user-role', '#project-user-' + thisId)
        .html($this.find('select'))
    });

  });
</script>
{% endif %}
{% endblock %}

{% block content %}

  {% if roster_formset %}
  <form method="post">
    <div style="display: none;">
      {% csrf_token %}
      {{ roster_formset.management_form }}

      {% for form in roster_formset.forms %}
      <div class="project-user-form">
        {{ form.id }}
        {{ form.project_role }}
      </div>
      {% endfor %}
    </div>
  {% endif %}

  <legend>{{ project.name }}</legend>
  <table class="table table-condensed table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>E-mail</th>
        <th>Role</th>
        <th>Joined</th>
        <th>Last login</th>
        <th>Active</th>
      </tr>
    </thead>
    <tbody>
      {% for user, role in roster %}
      <tr id="project-user-{{ user.id }}">
        <td>{{ user.as_text }}</td>
        <td>{{ user.email }}</td>
        <td class="project-user-role">{{ role.role|title }}</td>
        <td>{{ user.date_joined|date:"M j, Y" }}</td>
        <td>{{ user.last_login|date:"M j, Y" }}</td>
        <td>{{ user.is_active }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if roster_formset %}
  <p> <a href="{% url "admin:main_project_roles_change" project.slug %}">View/change roles</a> </p>
    <p> <input class="btn" type="submit" value="Save roster" /> </p>
  </form>
  {% endif %}

  <br />

  {% if invitation_formset %}
  <form class="project-invitations form-inline" method="post">
    {% csrf_token %}
    <legend>Project invitations</legend>
    {{ invitation_formset.management_form }}

    {% if invitation_formset|length > 1 %}
      <h5>Existing invitations</h5>
      <ol>
    {% endif %}

    {% for form in invitation_formset %}
    {% if forloop.last and invitation_formset|length > 1 %}</ol>{% endif %}
    <div class="project-invitation">

      {% if form.errors %}
      <div class="alert alert-error">
        {% for field in form %}
        {% if field.errors %}
        <p><strong>{{ field.label }}</strong>: {{ field.errors|striptags }}</p>
        {% endif %}
        {% endfor %}
      </div>
      {% endif %}

      {{ form.id }}
      {{ form.project.as_hidden }}

      {% if not forloop.last %}

        <li>
          Invited {{ form.instance.created|date:"F d, Y" }}: 
          {{ form.email.value }}
          {{ form.email.as_hidden }} {{ form.project_role.as_hidden }}
          &nbsp;
          <label for="{{ form.DELETE.auto_id }}"><strong>Delete?</strong> {{ form.DELETE }}</label>
        </li>

      {% else %}
        
        <h5>New invitation</h5>

        <p style="margin-left: 10px;">
          <label for="{{ form.email.auto_id }}">Email: </label> {{ form.email }}
          &nbsp;
          <label for="{{ form.project_role.auto_id }}">Project Role: </label> {{ form.project_role }}
          &nbsp;
        </p>

      {% endif %}

    </div>
    {% endfor %}
    <button type="submit" class="btn">Save invitations</button>
  </form>
  {% endif %}


{% endblock %}