cendari/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import RedirectView
from editorsnotes.main.views.auth import CustomBrowserIDVerify

from editorsnotes.main.views.topics import LegacyTopicRedirectView

from editorsnotes.admin.views.notes import NoteAdminView
#from editorsnotes.api.views.notes import NoteList


from cendari.views import NoteCendari,DocumentCendari, EditNoteAdminView, EditDocumentAdminView, EditTopicAdminView,  EditTranscriptAdminView
import cendari.views
import editorsnotes.admin.views
#admin.autodiscover()

# These will be intercepted by apache in production
urlpatterns = patterns('',
    (r'^favicon.ico$', RedirectView.as_view(url='/static/style/icons/favicon.ico')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT }),
    (r'^proxy$', 'editorsnotes.main.views.proxy'),
)


# Auth patterns
urlpatterns += patterns('',
    url(r'^accounts/login/$', 'cendari.views.user_login', name='user_login_view'),
    url(r'^accounts/logout/$', 'cendari.views.user_logout', name='user_logout_view'),
    url(r'^accounts/profile/$', 'editorsnotes.main.views.auth.user'),
    url(r'^accounts/profile/feedback/$', 'editorsnotes.main.views.auth.user_feedback', name='user_feedback_view'),
    url(r'^accounts/browserid/$', CustomBrowserIDVerify.as_view(), name='browserid_verify'),
    url(r'^user/(?P<username>[\w@\+\.\-]+)/$', 'editorsnotes.main.views.auth.user', name='user_view'),
)

#
# django-admin2 patterns
# 

USE_ADMIN2 = False
try:
    import djadmin2
    USE_ADMIN2 = True
except:
    pass

if USE_ADMIN2:
    import admin2
    urlpatterns += patterns('',
                            url(r'^admin2/', include(djadmin2.default.urls)))

# Base patterns
urlpatterns += patterns('editorsnotes.main.views.navigation',
    #url(r'^$', 'index', name='index_view'),
    url(r'^about/$', 'about', name='about_view'),
    url(r'^about/test/$', 'about_test'),
#    url(r'^search/$', 'search', name='search_view'),
    url(r'^version/$', 'get_version', name='get_version'),
)

# Admin patterns
urlpatterns += patterns('',
    url(r'^projects/(?P<project_slug>[-\w]+)/', include('editorsnotes.admin.urls', namespace='admin', app_name='admin')),
    url(r'^projects/add/', 'editorsnotes.admin.views.projects.add_project', name='add_project_view'),
)

# Main model patterns
urlpatterns += patterns('',
    url(r'^', include('editorsnotes.main.urls')),
)

# API
urlpatterns += patterns('',
    url(r'^api/', include('editorsnotes.api.urls', namespace='api', app_name='api')),
    url(r'^api/metadata/topics/types/$', 'editorsnotes.api.views.topics.topic_types'),
)

urlpatterns += patterns('editorsnotes.djotero.views',
#    url(r'^document/upload/$', 'import_zotero', name='import_zotero_view'),
#    url(r'^document/upload/libraries/$', 'libraries', name='libraries_view'),
#    url(r'^document/upload/collections/$', 'collections', name='collections_view'),
#    url(r'^document/upload/items/$', 'items', name='items_view'),
#    url(r'^document/upload/continue/$', 'items_continue', name='items_continue_view'),
#    url(r'^document/upload/import/$', 'import_items', name='import_items_view'),
    url(r'^user/zotero_info$', 'update_zotero_info', name='update_zotero_info_view'),
    url(r'^api/metadata/documents/item_template/$', 'item_template', name='item_template_view'),
    url(r'^api/metadata/documents/item_types/$', 'item_types', name='item_types_view'),
    url(r'^api/metadata/documents/item_type_creators/$', 'item_type_creators', name='item_type_creators_view'),
    url(r'^api/document/archives/$', 'api_archives', name='api_archives_view'),
)
urlpatterns += patterns('editorsnotes.refine.views',
   url(r'^cendari/(?P<project_slug>[-\w]+)/topics/clusters/$', 'show_topic_clusters', name='show_topic_clusters_view'),
   url(r'^cendari/topics/merge/(?P<cluster_id>\d+)/$', 'merge_topic_cluster', name='merge_topic_cluster_view'),
)

import editorsnotes.admin.views.projects

cendaripatterns = patterns('cendari.views',
    url(r'^$','index', name='index_view'),
    url(r'^browse/$', 'browse_cendari', name='cendari_browse_view'),
    url(r'^cendari/browse/$', 'browse_cendari', name='cendari_browse_view'),
    url(r'^about/$', 'about_cendari', name='cendari_about_view'),
    url(r'^cendari/about/$', 'about_cendari', name='cendari_about_view'),
    url(r'^cendari/external/(?P<type>\w+)/$', 'iframe_view', name='iframe_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/index$', 'index', name='index_project'),
    

    # Cendari Projects
    url(r'^cendari/projects/add/',                                                          'cendari_project_add',                name='add_project_view'),
    url(r'^cendari/projects/(?P<project_id>\d+)/$',                                          'cendari_project_change',            name='project_view'),
    url(r'^cendari/projects/(?P<project_slug>[-\w]+)/view/$',                                          'cendari_project_view',            name='project_read_view'),
    url(r'^cendari/projects/(?P<project_id>\d+)/add_alias/$',                                          'add_project_slug',            name='add_project_slug_view'),
    url(r'^projects/(?P<project_slug>[-\w]+)/',                                                 include('editorsnotes.admin.urls',   namespace='admin', app_name='admin')),
    #url(r'^cendari/projects/add/$',                                                         cendari.views.change_project,        name='addproject_view'),
    #url(r'^cendari/projects/(?P<slug>[-_a-z0-9]+)/$',                                       EditProjectAdminView.as_view(),      name='project_view'),

	# Cendari Notes
    #url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$',                          EditNoteAdminView.as_view(),         name='note_view'),
   # url(r'^cendari/(?P<project_slug>[-\w]+)/notes/add/$',                                       EditNoteAdminView.as_view(),         name='addnote_view'),
    #url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$',                          NoteCendari.as_view(),                    name='note_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/add/$',                                       NoteCendari.as_view(),                name='addnote_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/edit/$',                          'editNoteCendari',                name='note_edit'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/read/$',                          'readNoteCendari',                name='note_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$',                          'readNoteCendari',                name='note_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/version_history$',                          'versionHistoryNoteCendari',                name='note_version_history'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/version_history/(?P<version_id>\d+)$',  'versionNoteCendari',                name='note_version'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/rdfa/$', 'rdfa_view_note', name='rdfa_view_note'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/download/$', 'rdfa_download_note', name='rdfa_download_note'),

    # Cendari Documents
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/transcript/$',       EditTranscriptAdminView.as_view(),   name='transcript_edit_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/rdfa/$', 'rdfa_view_document', name='rdfa_view_document'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/download/$', 'rdfa_download_document', name='rdfa_download_document'),
   # url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/$',                  EditDocumentAdminView.as_view(),     name='document_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/edit/$',                 'editDocumentCendari',                name='document_edit'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/read/$',                 'readDocumentCendari',                name='document_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/$',                 'readDocumentCendari',                name='document_read'),
   # url(r'^cendari/(?P<project_slug>[-\w]+)/documents/add/$',                                   EditDocumentAdminView.as_view(),     name='adddocument_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/add/$',                                   DocumentCendari.as_view(),     name='adddocument_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/document/(?P<document_id>\d+)/version_history$',                          'versionHistoryDocumentCendari',                name='document_version_history'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/version_history/(?P<version_id>\d+)$',  'versionDocumentCendari',                name='document_version'),
    # Cendari Topics
    #url(r'^cendari/(?P<project_slug>[-\w]+)/topics/add/$',                                      EditTopicAdminView.as_view(),        name='addtopic_view'),
    #url(r'^cendari/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/$',                   EditTopicAdminView.as_view(),        name='topic_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/$',                   'readEntityCendari',                  name='topic_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/edit$',                   'editEntityCendari',                  name='topic_edit'),

editorsnotes/api/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url, include
import views

project_specific_patterns = patterns('',
    ### Project (general) ###
    url(r'^$', views.ProjectDetail.as_view(), name='api-project-detail'),
    url(r'^activity/$', views.ActivityView.as_view(), name='api-project-activity'),

    ### Topics ###
    url(r'^topics/$', views.TopicList.as_view(), name='api-topics-list'),
    url(r'^topics/(?P<topic_node_id>\d+)/$', views.TopicDetail.as_view(), name='api-topics-detail'),
    url(r'^topics/(?P<topic_node_id>\d+)/confirm_delete/$', views.TopicConfirmDelete.as_view(), name='api-topics-confirm-delete'),
    url(r'^topics/(?P<topic_node_id>\d+)/citations/$', views.TopicCitationList.as_view(), name='api-topic-citations-list'),
    url(r'^topics/(?P<topic_node_id>\d+)/citations/normalize_order/$', views.NormalizeCitationOrder.as_view(), name='api-topic-citations-normalize-order'),
    url(r'^topics/(?P<topic_node_id>\d+)/citations/(?P<citation_id>\d+)/$', views.TopicCitationDetail.as_view(), name='api-topic-citations-detail'),

    ### Notes ###
    url(r'^notes/$', views.NoteList.as_view(), name='api-notes-list'),
    url(r'^notes/(?P<pk>\d+)/$', views.NoteDetail.as_view(), name='api-notes-detail'),
    url(r'^notes/(?P<pk>\d+)/confirm_delete/$', views.NoteConfirmDelete.as_view(), name='api-notes-confirm-delete'),
    url(r'^notes/(?P<note_id>\d+)/s(?P<section_id>\d+)/$', views.NoteSectionDetail.as_view(), name='api-notes-section-detail'),
    url(r'^notes/(?P<note_id>\d+)/normalize_section_order/$', views.NormalizeSectionOrder.as_view(), name='api-notes-normalize-section-order'),

    ### Documents ###
    url(r'^documents/$', views.DocumentList.as_view(), name='api-documents-list'),
    url(r'^documents/(?P<pk>\d+)/$', views.DocumentDetail.as_view(), name='api-documents-detail'),
    url(r'^documents/(?P<pk>\d+)/confirm_delete/$', views.DocumentConfirmDelete.as_view(), name='api-documents-confirm-delete'),
    url(r'^documents/(?P<document_id>\d+)/scans/$', views.ScanList.as_view(), name='api-scans-list'),
    url(r'^documents/(?P<document_id>\d+)/scans/(?P<scan_id>\d+)/$', views.ScanDetail.as_view(), name='api-scans-detail'),
    url(r'^documents/(?P<document_id>\d+)/scans/normalize_order/$', views.NormalizeScanOrder.as_view(), name='api-scans-normalize-order'),
    # Cendari code E.G. aviz
    # added from the editors note repository
    url(r'^documents/(?P<document_id>\d+)/transcript/$', views.Transcript.as_view(), name='api-transcripts-detail'),
)

urlpatterns = patterns('',
    url(r'^$', views.base.root, name='api-root'),
    url(r'^auth-token/$', 'rest_framework.authtoken.views.obtain_auth_token', name='obtain-auth-token'),
    url(r'^search/$', views.SearchView.as_view(), name='api-search'),
    url(r'^topics/$', views.TopicNodeList.as_view(), name='api-topic-nodes-list'),
    url(r'^topics/(?P<pk>\d+)/$$', views.TopicNodeDetail.as_view(), name='api-topic-nodes-detail'),
    url(r'^projects/$', views.ProjectList.as_view(), name='api-projects-list'),
    url(r'^projects/(?P<project_slug>[-\w]+)/', include(project_specific_patterns)),
)

editorsnotes/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url, include
from django.conf import settings
from django.views.generic.base import RedirectView
from editorsnotes.main.views.auth import CustomBrowserIDVerify

# These will be intercepted by apache in production
urlpatterns = patterns('',
    (r'^favicon.ico$', RedirectView.as_view(url='/static/style/icons/favicon.ico')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT }),
    (r'^proxy$', 'editorsnotes.main.views.proxy'),
)

# Auth patterns
urlpatterns += patterns('',
  # CENDARI:old  url(r'^accounts/login/$', 'django.contrib.auth.views.login', { 'redirect_field_name': 'return_to' }),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', { 'redirect_field_name': 'return_to' }, name='user_login_view'),
    url(r'^accounts/logout/$', 'editorsnotes.main.views.auth.user_logout', name='user_logout_view'),
    url(r'^accounts/profile/$', 'editorsnotes.main.views.auth.user'),
    url(r'^accounts/profile/feedback/$', 'editorsnotes.main.views.auth.user_feedback', name='user_feedback_view'),
    url(r'^accounts/browserid/$', CustomBrowserIDVerify.as_view(), name='browserid_verify'),
    url(r'^user/(?P<username>[\w@\+\.\-]+)/$', 'editorsnotes.main.views.auth.user', name='user_view'),
)

# Base patterns
urlpatterns += patterns('editorsnotes.main.views.navigation',
#    url(r'^$', 'index', name='index_view'),
#    url(r'^about/$', 'about', name='about_view'),
#    url(r'^about/test/$', 'about_test'),
#    url(r'^search/$', 'search', name='search_view'),
    url(r'^version/$', 'get_version', name='get_version'),
)

# Admin patterns
urlpatterns += patterns('',
    url(r'^projects/(?P<project_slug>\w+)/', include('editorsnotes.admin.urls', namespace='admin', app_name='admin')),
    url(r'^projects/add/', 'editorsnotes.admin.views.projects.add_project', name='add_project_view'),
)

# Main model patterns
urlpatterns += patterns('',
    url(r'^', include('editorsnotes.main.urls')),
)

# API
urlpatterns += patterns('',
    url(r'^api/', include('editorsnotes.api.urls', namespace='api', app_name='api')),
    url(r'^api/metadata/topics/types/$', 'editorsnotes.api.views.topics.topic_types'),
)


urlpatterns += patterns('editorsnotes.djotero.views',
#    url(r'^document/upload/$', 'import_zotero', name='import_zotero_view'),
#    url(r'^document/upload/libraries/$', 'libraries', name='libraries_view'),
#    url(r'^document/upload/collections/$', 'collections', name='collections_view'),
#    url(r'^document/upload/items/$', 'items', name='items_view'),
#    url(r'^document/upload/continue/$', 'items_continue', name='items_continue_view'),
#    url(r'^document/upload/import/$', 'import_items', name='import_items_view'),
    url(r'^user/zotero_info$', 'update_zotero_info', name='update_zotero_info_view'),
    url(r'^api/metadata/documents/item_template/$', 'item_template', name='item_template_view'),
    url(r'^api/metadata/documents/item_types/$', 'item_types', name='item_types_view'),
    url(r'^api/metadata/documents/item_type_creators/$', 'item_type_creators', name='item_type_creators_view'),
    url(r'^api/document/archives/$', 'api_archives', name='api_archives_view'),
   # CENDARI:old url(r'^api/document/template/', 'zotero_template'),
   # CENDARI:old url(r'^api/document/blank/$', 'get_blank_item', name='get_blank_item_view'),
   # CENDARI:old url(r'^api/document/itemtypes/$', 'get_item_types'),
   # CENDARI:old url(r'^api/document/csl/$', 'zotero_json_to_csl', name='zotero_json_to_csl_view'),
   # CENDARI:old url(r'^api/document/archives/$', 'api_archives', name='api_archives_view'),
)
#urlpatterns += patterns('editorsnotes.refine.views',
#    url(r'^topics/clusters/$', 'show_topic_clusters', name='show_topic_clusters_view'),
#    url(r'^topics/merge/(?P<cluster_id>\d+)/$', 'merge_topic_cluster', name='merge_topic_cluster_view'),
#)

editorsnotes/main/forms.py
from django import forms

from .models.auth import UserFeedback

PURPOSE_CHOICES = (
    ('1', 'Feedback'),
    ('2', 'Bug report'),
    ('3', 'Request for account'),
    ('9', 'Other')
)

class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=50, label='Your name')
    email = forms.EmailField(label='Your email')
    purpose = forms.ChoiceField(choices=PURPOSE_CHOICES)
    message = forms.CharField(widget=forms.Textarea(
        attrs={'cols': '50', 'rows': '7', 'style': 'width: 50em;' }))

class UserFeedbackForm(forms.models.ModelForm):
    class Meta:
        model = UserFeedback

cendari/templates/cendari_chat.html
{% extends "djangoChat/index.html" %}

cendari/templates/editproject.html
{% extends "form.html" %}
{% load typogrify display %}
{% load staticfiles compress %}


{% block form_init %}
<meta name="project_id" id="project_id" content="{{ project.id }}" />


{% endblock form_init %}

{% block form_content %}

  {%if user_has_perm %}


    {% if form.errors %}
      {% for field in form %}
        {% for error in field.errors %}
          <div class="alert alert-error">
            <strong>{{ error|escape }}</strong>
            <strong>{{ field|escape }}</strong>
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-error">
          <strong>{{ error|escape }}</strong>
          <strong>{{ field|escape }}</strong>
        </div>
      {% endfor %}
    {% endif %}

    {{ form.as_p }}
    <!-- <input class="btn" type="submit" value="Save"> -->
    
    <br>
    <br>
   

  {% else %}

    <h1>Your are in project <u>{{project.name}}</u></h1>

  {%endif%}

   {% if mode == 'edit' %}
      <form class="formCendari" id="aliasSlugCendari" action="{% url "add_project_slug_view" project_id=project.id  %}" method="POST">
        <label for="slug_alias">New Alias:</label>
        <input id="id_slugalias" name="slug_alias" />
        <a id ="aliasSlugCendariSumbit" class="btn"   href="{% url "add_project_slug_view" project_id=project.id  %}"> Add</a>

        <h2> Available Slugs:</h2>
        <table style="width:100%" id='slug_alias_table'>
          <tr>
            <th><span style="font-weight:bold">Slug Alias</span></th>
            <th><span style="font-weight:bold">Project url</span></th>
          </tr>
          <tr>
            <td>{{project.slug}}</td>
            <td> <a href="{% url "project_read_view" project_slug=project.slug%}" target="_blank"> {% url "project_read_view" project_slug=project.slug%} </a> </td>
          </tr>
          {% for slug_alias in slug_aliases %}
            <tr>
              <td>{{slug_alias}}</td>
              <td> <a href="{% url "project_read_view" project_slug=slug_alias%}" target="_blank"> {% url "project_read_view" project_slug=slug_alias%} </a> </td>
            </tr>
          {% endfor %}

        </table>


       </form>
    {% endif%}
{% endblock form_content %}


{% block form_functions %}
<script>



(function ($) {

  var toastr_options = {
    "closeButton": true,
    "debug": false,
    "newestOnTop": true,
    "progressBar": false,
    "positionClass": "toast-top-center",
    "preventDuplicates": true,
    "onclick": null,
    "showDuration": "300",
    "hideDuration": "1000",
    "timeOut": "5000000000000000",
    "extendedTimeOut": "5000000000000000",
    "showEasing": "swing",
    "hideEasing": "linear",
    "showMethod": "fadeIn",
    "hideMethod": "fadeOut"
  }

  function showToastrMessage(type,message){
    toastr.clear();
    toastr[type](message);
  }

  function showErrorMessage(message){
    toastr.options.timeOut="1000";
    toastr.options.extendedTimeOut="1000";
    showToastrMessage('error',message);
  }

  function showSuccessMessage(message){
    toastr.options.timeOut="500";
    toastr.options.extendedTimeOut="1000";
    showToastrMessage('success',message);
  }


  function showWarningMessage(message){
    toastr.options.timeOut="5000";
    toastr.options.extendedTimeOut="10000";
    showToastrMessage('warning',message);
  }

  function showInfoMessage(message){
    toastr.options.timeOut="5000000000000000";
    toastr.options.extendedTimeOut="5000000000000000";
    showToastrMessage('info',message)
  }



  // custom css expression for a case-insensitive contains()
  jQuery.expr[':'].Contains = function(a,i,m){
      return (a.textContent || a.innerText || "").toUpperCase().indexOf(m[3].toUpperCase())>=0;
  };


  function listFilter(list) { // header is any element, list is an unordered list
    // create and add the filter form to the header
    var form = $("<form>").attr({"class":"filterform","action":"#"}),
        input = $("<input>").attr({"class":"filterinput","type":"text","placeholder":"Search for usernames"});
    $(form).append(input);//.appendTo(header);
    list.before($(form))
    $(input)
      .change( function () { 
        var filter = $(this).val();
        console.log('filter',filter);

        if(filter) {
          // this finds all links in a list that contain the input,
          // and hide the ones not containing the input while showing the ones that do
      		console.log('finding usernames');
          $(list).find("li:not(:Contains(" + filter + "))").slideUp();
          $(list).find("li:Contains(" + filter + ")").slideDown();

          console.log('contains filter',$(list).find("li:not(:Contains(" + filter + "))"))
          console.log('not contains filter', $(list).find("li:Contains(" + filter + ")"))

        } else {
        	$('#editors_selection').detach().appendTo('#noteform')
          	$(list).find("li").slideDown();
        }
        return false;
      })
    .keyup( function () {
        // fire the above change event after every letter
        $(this).change();
    });
  }


  //ondomready
  $(document).ready(function(){
  	console.log('Loading filter');
  	if($('#id_editors_0'))
    	listFilter($('#id_editors_0').closest('ul'));


    $('#aliasSlugCendariSumbit').on('click',function(e){
      e.preventDefault()
      $.ajax({
        // beforeSend: function (xhr) {xhr.setRequestHeader('X-CSRFToken', $('input[name="csrfmiddlewaretoken"]').val());},
        url:$('#aliasSlugCendariSumbit').attr('href'),
        type: 'POST',
        data: {project_id:{{project.id}},name:$('#id_slugalias').val(), csrfmiddlewaretoken: document.getElementsByName("csrfmiddlewaretoken")[0].value},
        success: function(data){
          console.log('data!!!')
          if (data['status'] == 'success'){
           $('#slug_alias_table').append('<tr>'+ '<td>'+$('#id_slugalias').val()+'</td>'+ '<td><a href="'+cendari_root_url+'cendari/'+$('#id_slugalias').val()+'" target="_blank"> '+cendari_root_url+'cendari/'+$('#id_slugalias').val()+' </a></td>'  +'</tr>')
           $('#id_slugalias').val('')
           showSuccessMessage('alias was added')
          }
          else{
            showErrorMessage(data['message'])
          }

        },
        error: function(XMLHttpRequest, textStatus, errorThrown) { 
            console.log("Error with status "+textStatus+":",errorThrown);
            // showErrorMessage(messages.transcript.error);
            showErrorMessage(errorThrown);
        } 
    });
    })
  })
  // $(function () {
  // 	console.log('Loading filter');
  //   listFilter($("#header"), $("#list"));
  // });
}(jQuery));






	

	cendari.addInit(function() {
		cendari.addTab("Project");
		cendari.addWidgetToActiveTab("form", "noteform", "border");
	}); 
	
	Ext.onReady(function(){
		$('#saveNoteID-btnEl').on('click',function(e){
			e.preventDefault();
			console.log($(this));
			$('#noteform').submit();
		})
	})
	
	$( document ).ready(function() {    
		
		if($('#id_slug').length){
			$('#id_name').keyup(function() {
	        	var dInput = $(this).val();
				$('#id_slug').val(dInput.replace(/[^a-zA-Z0-9-_]/g, '_'));
	
	
				if (event.which !== 0) {
	     		   console.log("Charcter was typed. It was: " + String.fromCharCode(e.which));
	    		}
	
			});
	
			$('#id_slug').keyup(function() {
	        	var dInput = $(this).val();
				$('#id_slug').val(dInput.replace(/[^a-zA-Z0-9-_]/g, '_'));
			});

		}
    if($('#id_slugalias').length){
      $('#id_slugalias').keyup(function() {
        var dInput = $(this).val();
        $('#id_slugalias').val(dInput.replace(/[^a-zA-Z0-9-_]/g, '_'));
      });
    }

	});
</script>
{% endblock form_functions %}

cendari/templates/emptylayout.html
{% extends "cendaribase.html" %}
{% load typogrify display %}
{% load staticfiles compress %}


{% block layout %}
	{% compress js %}
		<script type="text/javascript" src="{% static "cendari/js/nolayout.js" %}"></script>
	{% endcompress %}
		

	{% block nolayout_content %}
	{% endblock nolayout_content %}

{% endblock layout %}

cendari/templates/emptytab.html
{% extends "form.html" %}
{% load typogrify display %}
{% load staticfiles compress %}

{% block form_content %}

<meta name="note_id" id="note_id" content="{{ note.id }}" />
<input id="editorEditBut" type="button" value="Edit"/>


<div id="editorsDom">
</div>


<script>
    cendari.addInit(function() { 
    	cendari.addTab("My working space");
    	cendari.addWidgetToActiveTab("panel","editorsDom" ,"border");

    });

</script>

{% endblock %}