cendari/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import RedirectView
from editorsnotes.main.views.auth import CustomBrowserIDVerify

from editorsnotes.main.views.topics import LegacyTopicRedirectView

from editorsnotes.admin.views.notes import NoteAdminView
#from editorsnotes.api.views.notes import NoteList


from cendari.views import NoteCendari,DocumentCendari, EditNoteAdminView, EditDocumentAdminView, EditTopicAdminView,  EditTranscriptAdminView
import cendari.views
import editorsnotes.admin.views
#admin.autodiscover()

# These will be intercepted by apache in production
urlpatterns = patterns('',
    (r'^favicon.ico$', RedirectView.as_view(url='/static/style/icons/favicon.ico')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT }),
    (r'^proxy$', 'editorsnotes.main.views.proxy'),
)


# Auth patterns
urlpatterns += patterns('',
    url(r'^accounts/login/$', 'cendari.views.user_login', name='user_login_view'),
    url(r'^accounts/logout/$', 'cendari.views.user_logout', name='user_logout_view'),
    url(r'^accounts/profile/$', 'editorsnotes.main.views.auth.user'),
    url(r'^accounts/profile/feedback/$', 'editorsnotes.main.views.auth.user_feedback', name='user_feedback_view'),
    url(r'^accounts/browserid/$', CustomBrowserIDVerify.as_view(), name='browserid_verify'),
    url(r'^user/(?P<username>[\w@\+\.\-]+)/$', 'editorsnotes.main.views.auth.user', name='user_view'),
)

#
# django-admin2 patterns
# 

USE_ADMIN2 = False
try:
    import djadmin2
    USE_ADMIN2 = True
except:
    pass

if USE_ADMIN2:
    import admin2
    urlpatterns += patterns('',
                            url(r'^admin2/', include(djadmin2.default.urls)))

# Base patterns
urlpatterns += patterns('editorsnotes.main.views.navigation',
    #url(r'^$', 'index', name='index_view'),
    url(r'^about/$', 'about', name='about_view'),
    url(r'^about/test/$', 'about_test'),
#    url(r'^search/$', 'search', name='search_view'),
    url(r'^version/$', 'get_version', name='get_version'),
)

# Admin patterns
urlpatterns += patterns('',
    url(r'^projects/(?P<project_slug>[-\w]+)/', include('editorsnotes.admin.urls', namespace='admin', app_name='admin')),
    url(r'^projects/add/', 'editorsnotes.admin.views.projects.add_project', name='add_project_view'),
)

# Main model patterns
urlpatterns += patterns('',
    url(r'^', include('editorsnotes.main.urls')),
)

# API
urlpatterns += patterns('',
    url(r'^api/', include('editorsnotes.api.urls', namespace='api', app_name='api')),
    url(r'^api/metadata/topics/types/$', 'editorsnotes.api.views.topics.topic_types'),
)

urlpatterns += patterns('editorsnotes.djotero.views',
#    url(r'^document/upload/$', 'import_zotero', name='import_zotero_view'),
#    url(r'^document/upload/libraries/$', 'libraries', name='libraries_view'),
#    url(r'^document/upload/collections/$', 'collections', name='collections_view'),
#    url(r'^document/upload/items/$', 'items', name='items_view'),
#    url(r'^document/upload/continue/$', 'items_continue', name='items_continue_view'),
#    url(r'^document/upload/import/$', 'import_items', name='import_items_view'),
    url(r'^user/zotero_info$', 'update_zotero_info', name='update_zotero_info_view'),
    url(r'^api/metadata/documents/item_template/$', 'item_template', name='item_template_view'),
    url(r'^api/metadata/documents/item_types/$', 'item_types', name='item_types_view'),
    url(r'^api/metadata/documents/item_type_creators/$', 'item_type_creators', name='item_type_creators_view'),
    url(r'^api/document/archives/$', 'api_archives', name='api_archives_view'),
)
urlpatterns += patterns('editorsnotes.refine.views',
   url(r'^cendari/(?P<project_slug>[-\w]+)/topics/clusters/$', 'show_topic_clusters', name='show_topic_clusters_view'),
   url(r'^cendari/topics/merge/(?P<cluster_id>\d+)/$', 'merge_topic_cluster', name='merge_topic_cluster_view'),
)

import editorsnotes.admin.views.projects

cendaripatterns = patterns('cendari.views',
    url(r'^$','index', name='index_view'),
    url(r'^browse/$', 'browse_cendari', name='cendari_browse_view'),
    url(r'^cendari/browse/$', 'browse_cendari', name='cendari_browse_view'),
    url(r'^about/$', 'about_cendari', name='cendari_about_view'),
    url(r'^cendari/about/$', 'about_cendari', name='cendari_about_view'),
    url(r'^cendari/external/(?P<type>\w+)/$', 'iframe_view', name='iframe_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/index$', 'index', name='index_project'),
    

    # Cendari Projects
    url(r'^cendari/projects/add/',                                                          'cendari_project_add',                name='add_project_view'),
    url(r'^cendari/projects/(?P<project_id>\d+)/$',                                          'cendari_project_change',            name='project_view'),
    url(r'^cendari/projects/(?P<project_slug>[-\w]+)/view/$',                                          'cendari_project_view',            name='project_read_view'),
    url(r'^cendari/projects/(?P<project_id>\d+)/add_alias/$',                                          'add_project_slug',            name='add_project_slug_view'),
    url(r'^projects/(?P<project_slug>[-\w]+)/',                                                 include('editorsnotes.admin.urls',   namespace='admin', app_name='admin')),
    #url(r'^cendari/projects/add/$',                                                         cendari.views.change_project,        name='addproject_view'),
    #url(r'^cendari/projects/(?P<slug>[-_a-z0-9]+)/$',                                       EditProjectAdminView.as_view(),      name='project_view'),

	# Cendari Notes
    #url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$',                          EditNoteAdminView.as_view(),         name='note_view'),
   # url(r'^cendari/(?P<project_slug>[-\w]+)/notes/add/$',                                       EditNoteAdminView.as_view(),         name='addnote_view'),
    #url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$',                          NoteCendari.as_view(),                    name='note_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/add/$',                                       NoteCendari.as_view(),                name='addnote_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/edit/$',                          'editNoteCendari',                name='note_edit'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/read/$',                          'readNoteCendari',                name='note_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$',                          'readNoteCendari',                name='note_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/version_history$',                          'versionHistoryNoteCendari',                name='note_version_history'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/version_history/(?P<version_id>\d+)$',  'versionNoteCendari',                name='note_version'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/rdfa/$', 'rdfa_view_note', name='rdfa_view_note'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/download/$', 'rdfa_download_note', name='rdfa_download_note'),

    # Cendari Documents
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/transcript/$',       EditTranscriptAdminView.as_view(),   name='transcript_edit_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/rdfa/$', 'rdfa_view_document', name='rdfa_view_document'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/download/$', 'rdfa_download_document', name='rdfa_download_document'),
   # url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/$',                  EditDocumentAdminView.as_view(),     name='document_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/edit/$',                 'editDocumentCendari',                name='document_edit'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/read/$',                 'readDocumentCendari',                name='document_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/$',                 'readDocumentCendari',                name='document_read'),
   # url(r'^cendari/(?P<project_slug>[-\w]+)/documents/add/$',                                   EditDocumentAdminView.as_view(),     name='adddocument_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/add/$',                                   DocumentCendari.as_view(),     name='adddocument_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/document/(?P<document_id>\d+)/version_history$',                          'versionHistoryDocumentCendari',                name='document_version_history'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/version_history/(?P<version_id>\d+)$',  'versionDocumentCendari',                name='document_version'),
    # Cendari Topics
    #url(r'^cendari/(?P<project_slug>[-\w]+)/topics/add/$',                                      EditTopicAdminView.as_view(),        name='addtopic_view'),
    #url(r'^cendari/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/$',                   EditTopicAdminView.as_view(),        name='topic_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/$',                   'readEntityCendari',                  name='topic_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/edit$',                   'editEntityCendari',                  name='topic_edit'),

editorsnotes/admin/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^edit/$', views.projects.change_project, name='main_project_change'),
    url(r'^roster/$', views.projects.project_roster, name='main_project_roster_change'),
    url(r'^roles/$', views.projects.change_project_roles, name='main_project_roles_change'),
    url(r'^featured_items/$', views.projects.change_featured_items, name='main_featured_items_change'),
    url(r'^topics/add/$', views.topics.TopicAdminView.as_view(), name='main_topic_add'),
    url(r'^topics/(?P<topic_node_id>\d+)/edit/$', views.topics.TopicAdminView.as_view(), name='main_topic_change'),
    url(r'^documents/add/$', views.documents.DocumentAdminView.as_view(), name='main_document_add'),
    url(r'^documents/(?P<document_id>\d+)/edit/$', views.documents.DocumentAdminView.as_view(), name='main_document_change'),
    url(r'^documents/(?P<document_id>\d+)/transcript/edit/$', views.documents.TranscriptAdminView.as_view(), name='main_transcript_add_or_change'),
    url(r'^notes/add/$', views.notes.NoteAdminView.as_view(), name='main_note_add'),
    url(r'^notes/(?P<note_id>\d+)/edit/$', views.notes.NoteAdminView.as_view(), name='main_note_change'),
)

editorsnotes/main/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url

from views.topics import LegacyTopicRedirectView

urlpatterns = patterns('editorsnotes.main.views.auth',
    url(r'^feedback/$', 'all_feedback', name='all_feedback_view'),
    url(r'^projects/$', 'all_projects', name='all_projects_view'),
    url(r'^projects/(?P<project_slug>[-\w]+)/$', 'project', name='project_view'),
)

#urlpatterns += patterns('editorsnotes.main.views.navigation',
#    url(r'^browse/$', 'browse', name='browse_view'),
#)

urlpatterns += patterns('editorsnotes.main.views.documents',
    url(r'^(?:projects/(?P<project_slug>[-\w]+)/)?documents/$', 'all_documents', name='all_documents_view'),
    url(r'^projects/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/$', 'document', name='document_view'),
    url(r'^projects/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/transcript/$', 'transcript', name='transcript_view'),
    url(r'^projects/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/footnotes/(?P<footnote_id>\d+)/$', 'footnote', name='footnote_view'),
)

urlpatterns += patterns('editorsnotes.main.views.notes',
    url(r'^(?:projects/(?P<project_slug>[-\w]+)/)?notes/$', 'all_notes', name='all_notes_view'),
    url(r'^projects/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$', 'note', name='note_view'),
)

urlpatterns += patterns('editorsnotes.main.views.topics',
    url(r'^(?:projects/(?P<project_slug>[-\w]+)/)?topics/$', 'all_topics', name='all_topics_view'),
    url(r'^topics/(?P<topic_node_id>\d+)/$', 'topic_node', name='topic_node_view'),
    url(r'^projects/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/$', 'topic', name='topic_view'),
    url(r'^topic/(?P<topic_slug>[-\w,]+)/$', LegacyTopicRedirectView.as_view(), name='legacy_topic_view'),
)

editorsnotes/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url, include
from django.conf import settings
from django.views.generic.base import RedirectView
from editorsnotes.main.views.auth import CustomBrowserIDVerify

# These will be intercepted by apache in production
urlpatterns = patterns('',
    (r'^favicon.ico$', RedirectView.as_view(url='/static/style/icons/favicon.ico')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT }),
    (r'^proxy$', 'editorsnotes.main.views.proxy'),
)

# Auth patterns
urlpatterns += patterns('',
  # CENDARI:old  url(r'^accounts/login/$', 'django.contrib.auth.views.login', { 'redirect_field_name': 'return_to' }),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', { 'redirect_field_name': 'return_to' }, name='user_login_view'),
    url(r'^accounts/logout/$', 'editorsnotes.main.views.auth.user_logout', name='user_logout_view'),
    url(r'^accounts/profile/$', 'editorsnotes.main.views.auth.user'),
    url(r'^accounts/profile/feedback/$', 'editorsnotes.main.views.auth.user_feedback', name='user_feedback_view'),
    url(r'^accounts/browserid/$', CustomBrowserIDVerify.as_view(), name='browserid_verify'),
    url(r'^user/(?P<username>[\w@\+\.\-]+)/$', 'editorsnotes.main.views.auth.user', name='user_view'),
)

# Base patterns
urlpatterns += patterns('editorsnotes.main.views.navigation',
#    url(r'^$', 'index', name='index_view'),
#    url(r'^about/$', 'about', name='about_view'),
#    url(r'^about/test/$', 'about_test'),
#    url(r'^search/$', 'search', name='search_view'),
    url(r'^version/$', 'get_version', name='get_version'),
)

# Admin patterns
urlpatterns += patterns('',
    url(r'^projects/(?P<project_slug>\w+)/', include('editorsnotes.admin.urls', namespace='admin', app_name='admin')),
    url(r'^projects/add/', 'editorsnotes.admin.views.projects.add_project', name='add_project_view'),
)

# Main model patterns
urlpatterns += patterns('',
    url(r'^', include('editorsnotes.main.urls')),
)

# API
urlpatterns += patterns('',
    url(r'^api/', include('editorsnotes.api.urls', namespace='api', app_name='api')),
    url(r'^api/metadata/topics/types/$', 'editorsnotes.api.views.topics.topic_types'),
)


urlpatterns += patterns('editorsnotes.djotero.views',
#    url(r'^document/upload/$', 'import_zotero', name='import_zotero_view'),
#    url(r'^document/upload/libraries/$', 'libraries', name='libraries_view'),
#    url(r'^document/upload/collections/$', 'collections', name='collections_view'),
#    url(r'^document/upload/items/$', 'items', name='items_view'),
#    url(r'^document/upload/continue/$', 'items_continue', name='items_continue_view'),
#    url(r'^document/upload/import/$', 'import_items', name='import_items_view'),
    url(r'^user/zotero_info$', 'update_zotero_info', name='update_zotero_info_view'),
    url(r'^api/metadata/documents/item_template/$', 'item_template', name='item_template_view'),
    url(r'^api/metadata/documents/item_types/$', 'item_types', name='item_types_view'),
    url(r'^api/metadata/documents/item_type_creators/$', 'item_type_creators', name='item_type_creators_view'),
    url(r'^api/document/archives/$', 'api_archives', name='api_archives_view'),
   # CENDARI:old url(r'^api/document/template/', 'zotero_template'),
   # CENDARI:old url(r'^api/document/blank/$', 'get_blank_item', name='get_blank_item_view'),
   # CENDARI:old url(r'^api/document/itemtypes/$', 'get_item_types'),
   # CENDARI:old url(r'^api/document/csl/$', 'zotero_json_to_csl', name='zotero_json_to_csl_view'),
   # CENDARI:old url(r'^api/document/archives/$', 'api_archives', name='api_archives_view'),
)
#urlpatterns += patterns('editorsnotes.refine.views',
#    url(r'^topics/clusters/$', 'show_topic_clusters', name='show_topic_clusters_view'),
#    url(r'^topics/merge/(?P<cluster_id>\d+)/$', 'merge_topic_cluster', name='merge_topic_cluster_view'),
#)

editorsnotes/main/forms.py
from django import forms

from .models.auth import UserFeedback

PURPOSE_CHOICES = (
    ('1', 'Feedback'),
    ('2', 'Bug report'),
    ('3', 'Request for account'),
    ('9', 'Other')
)

class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=50, label='Your name')
    email = forms.EmailField(label='Your email')
    purpose = forms.ChoiceField(choices=PURPOSE_CHOICES)
    message = forms.CharField(widget=forms.Textarea(
        attrs={'cols': '50', 'rows': '7', 'style': 'width: 50em;' }))

class UserFeedbackForm(forms.models.ModelForm):
    class Meta:
        model = UserFeedback

editorsnotes/main/templates/document.html
{% extends "base.html" %}
{% load typogrify display %}

{% block title %}: {{ document }}{% endblock %}

{% block css %}
<style type="text/css">
  #transcript-content {
    position: relative;
  }
  a.footnote:hover {
    color: red;
    text-decoration: none;
  }
  a.footnote:before {
    content: ' \25CF';
    font-size: 10px;
    color: red;
    position: absolute;
    left: -12px;
  }
  .footnote-number sup {
    color: red;
  }
  #footnotediv {
    background-color: white;
    border: 1px solid #CDBBB5;
    -webkit-box-shadow: #555 0px 0px 10px;
    padding: 10px;
    margin: 0 auto 0 auto;
  }
  #footnotediv p {
    margin: 0;
  }
  .popover-inner {
    width: auto;
    max-width: 600px;
  }
  .arrow {
    display: none;
  }
</style>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{{ STATIC_URL }}function/lib/seadragon/seadragon-min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}function/document.js"></script>
{% endblock %}

{% block content %}

    <header>
      <h2>{{ document.description|as_html|typogrify }}</h2>
      <div class="related-topics">
        {% if topics %}
        <span class="quiet">Related topics:</span> 
        <ul class="topic-list unstyled">
          {% for topic in topics %}
          <li>
            <a href="{{ topic.get_absolute_url }}">
              {{ topic.preferred_name }}
            </a>
            {% if not forloop.last %} | {% endif %}
          </li>
          {% endfor %}
        </ul>
        {% endif %}
      </div>    
    </header>

      <ul id="tabs" class="nav nav-tabs">
        <li class="active"><a href="#info-tab" data-toggle="tab">Info</a></li>

        {% if document.has_parts %}
        <li><a href="#parts-tab" data-toggle="tab">Parts</a></li>
        {% endif %}

        {% if scans %}
        <li><a href="#scans-tab" data-toggle="tab">Scans</a></li>
        {% endif %}

        {% if document.transcript %}
        <li><a href="#transcript-tab" data-toggle="tab">Transcript</a></li>
        {% endif %}

        <li><a href="#notes-tab" data-toggle="tab">Related Notes <span class="alt">&amp;</span> Queries ({{ notes|length }})</a></li>
      </ul>

      <div class="tab-content">
        <section id="info-tab" class="tab-pane active">
          <div id="zotero">
            {% if zotero_data %}
              {% include "zotero_item.html" %}
            {% else %}
            <p>This document has no connected Zotero data.</p>
            {% endif %}
          </div>

          <div>
            {% if document.has_links %}
            <h4>External link{% if document.links.count > 1 %}s{% endif %}</h4>
            <ul class="unstyled">
              {% for link in document.links.all %}
              <li>
                <a style="text-decoration: underline;" href="{{ link }}">{{ link }}</a>
                <div>
                  {{ link.description }}
                </div>
              </li>
              {% endfor %}
            </ul>
            {% endif %}
          </div>

          <div class="row edit-row">
            <div class="span6 edit-button">
              {% if request.user.is_authenticated %}
              <a class="btn" href="{{ document.get_admin_url }}?return_to={{ document.get_absolute_url }}">Edit</a>
              {% endif %}
            </div>
            <div class="span6 edit-history">
              {{ document|display_edit_history }}
            </div>
          </div>

        </section>

        {% if document.has_parts %}
        <section id="parts-tab" class="tab-pane">
          <div id="scanlist-container">
            <ul id="parts-list">
              {% for part in document.parts.all %}
              <li>{{ part|as_link }}</li>
              {% endfor %}
            </ul>
          </div>
          {% if request.user.is_authenticated %}
          <a class="btn" href="{{ document.get_admin_url }}?return_to={{ document.get_absolute_url }}">Edit</a>
          {% endif %}
        </section>
        {% endif %}

        {% if scans %}
        <section id="scans-tab" class="tab-pane">
          <div id="scanlist-container">
            <ul id="scan-list">
              {% for scan in scans %}
              <li>
                <a class="scan btn"
                  href="http://{{ domain }}{{ scan.image.url }}">
                  {{ forloop.counter }}
                </a>
              </li>
              {% endfor %}
            </ul>
          </div>

          <br/>

          <div id="scan-viewer" style="height: 500px;"></div>
          <div id="progress-notify">
            <span id="progress-message">Loading scanned document...</span>
            <div id="progressbar"></div>
          </div>
        </section>
        {% endif %}

        {% if document.transcript %}
        <section id="transcript-tab" class="tab-pane">
          <article id="transcript-{{ document.transcript.id }}" class="transcript">
            <div id="transcript-content">
              {{ document.transcript.content|as_html|typogrify }}
            </div>
            <div id="transcript-notes">
              {% for note in document.transcript.get_footnotes %}
              <div id="note-{{ note.id }}" class="transcript-note hide"> 
                {{ note.content|as_html|typogrify }}
              </div>
              {% endfor %}
            </div>
            <div>
              {% if user.is_authenticated %}
              <a class="btn" href="{% url "admin:main_transcript_add_or_change" document.project.slug document.id %}?return_to={{ document.get_absolute_url }}">Edit transcript</a>
              {% endif %}
              <div class="edit-history">
                {{ document.transcript|display_edit_history }}
              </div>
            </div>
          </article>
        </section>
        {% endif %}

        <section id="notes-tab" class="tab-pane">
        {% if notes %}
          {% for note, topics in notes %}
          <div id="note-{{ note.id }}" class="related-note">
            <div class="note-link">
              <a href="{{ note.get_absolute_url }}">{{ note.title}}</a>
            </div>
            <div class="note-last-modified">
              <span class="quiet">Last modified: </span><span>{{ note.last_updated|date:"F j, Y" }}</span>
            </div>
            {% if topics %}
            <div class="note-topics">
              <span class="quiet">Related topics: </span>
              <ul class="topic-list unstyled">
                {% for topic in topics %}
                  <li>{{ topic|as_link }}</a>{% if not forloop.last %} | {% endif %}</li>
                {% endfor %}
              </ul>
            </div>
            {% endif %}
          </div>
          {% endfor %}
        {% else %}
          There are no notes or queries related to this document.
        {% endif %}
        </section>
      </div>
{% endblock %}

editorsnotes/main/templates/logout.html
{% extends "base.html" %}
{% block content %}
You are now logged out.
{% endblock %}

editorsnotes/main/templates/project.html
{% extends "base.html" %}

{% load display typogrify %}

{% block content %}
<h1>{{ project.name }}</h1>
<hr/>

{% if show_edit_row %}
<div class="well">
  {% if project_role %}
  <p>
  You are a member of this project, with the role: <strong>{{ project_role.role }}</strong>. You may perform the following actions.
  </p>
  {% endif %}
  <div>
    {% if can_change_roster or can_view_roster %}
    <a class="btn" href="{% url "admin:main_project_roster_change" project.slug %}">
      <i class="fa fa-user"></i>
      {% if can_change_roster %}Edit{% else %}View{% endif %} roster
    </a>
    {% endif %}

    {% if can_change_project %}
    <a class="btn" href="{% url "admin:main_project_change" project.slug %}">
      <i class="fa fa-pencil-square-o"></i>
      Edit project description
    </a>
    {% endif %}

    {% if can_change_featured_items %}
    <a class="btn" href="{% url "admin:main_featured_items_change" project.slug %}">
      <i class="fa fa-star"></i>
      Select featured items
    </a>
    {% endif %}

  </div>
</div>
{% endif %}

<div class="row">
  <div class="span6">
    {% if project.has_description %}
      {% if project.image %}
        <img align="left" style="margin: 0 10px 10px 0;" src="{{ project.image.url }}" />
      {% endif %}
      {{ project.description|as_html|typogrify }}
    {% else %}
      no project description
    {% endif %}
  </div>
  <div class="span6">
    {% with project.featureditem_set.all as featured_items %}
      {% if featured_items %}
        <h3>&#9733; Featured items</h3>
        {% for item in featured_items %}
        <ul class="unstyled model-item-list">
          <li><span class="model-label">{{ item.content_object|object_name}}:</span> {{ item.content_object|as_link }}</li>
        </ul>
        {% endfor %}
        <hr/>
      {% else %}
      {% endif %}

    {% endwith %}

    <h3>Recent edits</h3>
    {% include "includes/activity.html" %}
  </div>
</div>


{% endblock %}