cendari/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import RedirectView
from editorsnotes.main.views.auth import CustomBrowserIDVerify

from editorsnotes.main.views.topics import LegacyTopicRedirectView

from editorsnotes.admin.views.notes import NoteAdminView
#from editorsnotes.api.views.notes import NoteList


from cendari.views import NoteCendari,DocumentCendari, EditNoteAdminView, EditDocumentAdminView, EditTopicAdminView,  EditTranscriptAdminView
import cendari.views
import editorsnotes.admin.views
#admin.autodiscover()

# These will be intercepted by apache in production
urlpatterns = patterns('',
    (r'^favicon.ico$', RedirectView.as_view(url='/static/style/icons/favicon.ico')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT }),
    (r'^proxy$', 'editorsnotes.main.views.proxy'),
)


# Auth patterns
urlpatterns += patterns('',
    url(r'^accounts/login/$', 'cendari.views.user_login', name='user_login_view'),
    url(r'^accounts/logout/$', 'cendari.views.user_logout', name='user_logout_view'),
    url(r'^accounts/profile/$', 'editorsnotes.main.views.auth.user'),
    url(r'^accounts/profile/feedback/$', 'editorsnotes.main.views.auth.user_feedback', name='user_feedback_view'),
    url(r'^accounts/browserid/$', CustomBrowserIDVerify.as_view(), name='browserid_verify'),
    url(r'^user/(?P<username>[\w@\+\.\-]+)/$', 'editorsnotes.main.views.auth.user', name='user_view'),
)

#
# django-admin2 patterns
# 

USE_ADMIN2 = False
try:
    import djadmin2
    USE_ADMIN2 = True
except:
    pass

if USE_ADMIN2:
    import admin2
    urlpatterns += patterns('',
                            url(r'^admin2/', include(djadmin2.default.urls)))

# Base patterns
urlpatterns += patterns('editorsnotes.main.views.navigation',
    #url(r'^$', 'index', name='index_view'),
    url(r'^about/$', 'about', name='about_view'),
    url(r'^about/test/$', 'about_test'),
#    url(r'^search/$', 'search', name='search_view'),
    url(r'^version/$', 'get_version', name='get_version'),
)

# Admin patterns
urlpatterns += patterns('',
    url(r'^projects/(?P<project_slug>[-\w]+)/', include('editorsnotes.admin.urls', namespace='admin', app_name='admin')),
    url(r'^projects/add/', 'editorsnotes.admin.views.projects.add_project', name='add_project_view'),
)

# Main model patterns
urlpatterns += patterns('',
    url(r'^', include('editorsnotes.main.urls')),
)

# API
urlpatterns += patterns('',
    url(r'^api/', include('editorsnotes.api.urls', namespace='api', app_name='api')),
    url(r'^api/metadata/topics/types/$', 'editorsnotes.api.views.topics.topic_types'),
)

urlpatterns += patterns('editorsnotes.djotero.views',
#    url(r'^document/upload/$', 'import_zotero', name='import_zotero_view'),
#    url(r'^document/upload/libraries/$', 'libraries', name='libraries_view'),
#    url(r'^document/upload/collections/$', 'collections', name='collections_view'),
#    url(r'^document/upload/items/$', 'items', name='items_view'),
#    url(r'^document/upload/continue/$', 'items_continue', name='items_continue_view'),
#    url(r'^document/upload/import/$', 'import_items', name='import_items_view'),
    url(r'^user/zotero_info$', 'update_zotero_info', name='update_zotero_info_view'),
    url(r'^api/metadata/documents/item_template/$', 'item_template', name='item_template_view'),
    url(r'^api/metadata/documents/item_types/$', 'item_types', name='item_types_view'),
    url(r'^api/metadata/documents/item_type_creators/$', 'item_type_creators', name='item_type_creators_view'),
    url(r'^api/document/archives/$', 'api_archives', name='api_archives_view'),
)
urlpatterns += patterns('editorsnotes.refine.views',
   url(r'^cendari/(?P<project_slug>[-\w]+)/topics/clusters/$', 'show_topic_clusters', name='show_topic_clusters_view'),
   url(r'^cendari/topics/merge/(?P<cluster_id>\d+)/$', 'merge_topic_cluster', name='merge_topic_cluster_view'),
)

import editorsnotes.admin.views.projects

cendaripatterns = patterns('cendari.views',
    url(r'^$','index', name='index_view'),
    url(r'^browse/$', 'browse_cendari', name='cendari_browse_view'),
    url(r'^cendari/browse/$', 'browse_cendari', name='cendari_browse_view'),
    url(r'^about/$', 'about_cendari', name='cendari_about_view'),
    url(r'^cendari/about/$', 'about_cendari', name='cendari_about_view'),
    url(r'^cendari/external/(?P<type>\w+)/$', 'iframe_view', name='iframe_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/index$', 'index', name='index_project'),
    

    # Cendari Projects
    url(r'^cendari/projects/add/',                                                          'cendari_project_add',                name='add_project_view'),
    url(r'^cendari/projects/(?P<project_id>\d+)/$',                                          'cendari_project_change',            name='project_view'),
    url(r'^cendari/projects/(?P<project_slug>[-\w]+)/view/$',                                          'cendari_project_view',            name='project_read_view'),
    url(r'^cendari/projects/(?P<project_id>\d+)/add_alias/$',                                          'add_project_slug',            name='add_project_slug_view'),
    url(r'^projects/(?P<project_slug>[-\w]+)/',                                                 include('editorsnotes.admin.urls',   namespace='admin', app_name='admin')),
    #url(r'^cendari/projects/add/$',                                                         cendari.views.change_project,        name='addproject_view'),
    #url(r'^cendari/projects/(?P<slug>[-_a-z0-9]+)/$',                                       EditProjectAdminView.as_view(),      name='project_view'),

	# Cendari Notes
    #url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$',                          EditNoteAdminView.as_view(),         name='note_view'),
   # url(r'^cendari/(?P<project_slug>[-\w]+)/notes/add/$',                                       EditNoteAdminView.as_view(),         name='addnote_view'),
    #url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$',                          NoteCendari.as_view(),                    name='note_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/add/$',                                       NoteCendari.as_view(),                name='addnote_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/edit/$',                          'editNoteCendari',                name='note_edit'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/read/$',                          'readNoteCendari',                name='note_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/$',                          'readNoteCendari',                name='note_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/version_history$',                          'versionHistoryNoteCendari',                name='note_version_history'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/version_history/(?P<version_id>\d+)$',  'versionNoteCendari',                name='note_version'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/rdfa/$', 'rdfa_view_note', name='rdfa_view_note'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/notes/(?P<note_id>\d+)/download/$', 'rdfa_download_note', name='rdfa_download_note'),

    # Cendari Documents
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/transcript/$',       EditTranscriptAdminView.as_view(),   name='transcript_edit_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/rdfa/$', 'rdfa_view_document', name='rdfa_view_document'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/download/$', 'rdfa_download_document', name='rdfa_download_document'),
   # url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/$',                  EditDocumentAdminView.as_view(),     name='document_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/edit/$',                 'editDocumentCendari',                name='document_edit'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/read/$',                 'readDocumentCendari',                name='document_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/$',                 'readDocumentCendari',                name='document_read'),
   # url(r'^cendari/(?P<project_slug>[-\w]+)/documents/add/$',                                   EditDocumentAdminView.as_view(),     name='adddocument_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/add/$',                                   DocumentCendari.as_view(),     name='adddocument_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/document/(?P<document_id>\d+)/version_history$',                          'versionHistoryDocumentCendari',                name='document_version_history'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/documents/(?P<document_id>\d+)/version_history/(?P<version_id>\d+)$',  'versionDocumentCendari',                name='document_version'),
    # Cendari Topics
    #url(r'^cendari/(?P<project_slug>[-\w]+)/topics/add/$',                                      EditTopicAdminView.as_view(),        name='addtopic_view'),
    #url(r'^cendari/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/$',                   EditTopicAdminView.as_view(),        name='topic_view'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/$',                   'readEntityCendari',                  name='topic_read'),
    url(r'^cendari/(?P<project_slug>[-\w]+)/topics/(?P<topic_node_id>\d+)/edit$',                   'editEntityCendari',                  name='topic_edit'),

editorsnotes/api/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url, include
import views

project_specific_patterns = patterns('',
    ### Project (general) ###
    url(r'^$', views.ProjectDetail.as_view(), name='api-project-detail'),
    url(r'^activity/$', views.ActivityView.as_view(), name='api-project-activity'),

    ### Topics ###
    url(r'^topics/$', views.TopicList.as_view(), name='api-topics-list'),
    url(r'^topics/(?P<topic_node_id>\d+)/$', views.TopicDetail.as_view(), name='api-topics-detail'),
    url(r'^topics/(?P<topic_node_id>\d+)/confirm_delete/$', views.TopicConfirmDelete.as_view(), name='api-topics-confirm-delete'),
    url(r'^topics/(?P<topic_node_id>\d+)/citations/$', views.TopicCitationList.as_view(), name='api-topic-citations-list'),
    url(r'^topics/(?P<topic_node_id>\d+)/citations/normalize_order/$', views.NormalizeCitationOrder.as_view(), name='api-topic-citations-normalize-order'),
    url(r'^topics/(?P<topic_node_id>\d+)/citations/(?P<citation_id>\d+)/$', views.TopicCitationDetail.as_view(), name='api-topic-citations-detail'),

    ### Notes ###
    url(r'^notes/$', views.NoteList.as_view(), name='api-notes-list'),
    url(r'^notes/(?P<pk>\d+)/$', views.NoteDetail.as_view(), name='api-notes-detail'),
    url(r'^notes/(?P<pk>\d+)/confirm_delete/$', views.NoteConfirmDelete.as_view(), name='api-notes-confirm-delete'),
    url(r'^notes/(?P<note_id>\d+)/s(?P<section_id>\d+)/$', views.NoteSectionDetail.as_view(), name='api-notes-section-detail'),
    url(r'^notes/(?P<note_id>\d+)/normalize_section_order/$', views.NormalizeSectionOrder.as_view(), name='api-notes-normalize-section-order'),

    ### Documents ###
    url(r'^documents/$', views.DocumentList.as_view(), name='api-documents-list'),
    url(r'^documents/(?P<pk>\d+)/$', views.DocumentDetail.as_view(), name='api-documents-detail'),
    url(r'^documents/(?P<pk>\d+)/confirm_delete/$', views.DocumentConfirmDelete.as_view(), name='api-documents-confirm-delete'),
    url(r'^documents/(?P<document_id>\d+)/scans/$', views.ScanList.as_view(), name='api-scans-list'),
    url(r'^documents/(?P<document_id>\d+)/scans/(?P<scan_id>\d+)/$', views.ScanDetail.as_view(), name='api-scans-detail'),
    url(r'^documents/(?P<document_id>\d+)/scans/normalize_order/$', views.NormalizeScanOrder.as_view(), name='api-scans-normalize-order'),
    # Cendari code E.G. aviz
    # added from the editors note repository
    url(r'^documents/(?P<document_id>\d+)/transcript/$', views.Transcript.as_view(), name='api-transcripts-detail'),
)

urlpatterns = patterns('',
    url(r'^$', views.base.root, name='api-root'),
    url(r'^auth-token/$', 'rest_framework.authtoken.views.obtain_auth_token', name='obtain-auth-token'),
    url(r'^search/$', views.SearchView.as_view(), name='api-search'),
    url(r'^topics/$', views.TopicNodeList.as_view(), name='api-topic-nodes-list'),
    url(r'^topics/(?P<pk>\d+)/$$', views.TopicNodeDetail.as_view(), name='api-topic-nodes-detail'),
    url(r'^projects/$', views.ProjectList.as_view(), name='api-projects-list'),
    url(r'^projects/(?P<project_slug>[-\w]+)/', include(project_specific_patterns)),
)

editorsnotes/urls.py
# vim: set tw=0:

from django.conf.urls import patterns, url, include
from django.conf import settings
from django.views.generic.base import RedirectView
from editorsnotes.main.views.auth import CustomBrowserIDVerify

# These will be intercepted by apache in production
urlpatterns = patterns('',
    (r'^favicon.ico$', RedirectView.as_view(url='/static/style/icons/favicon.ico')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT }),
    (r'^proxy$', 'editorsnotes.main.views.proxy'),
)

# Auth patterns
urlpatterns += patterns('',
  # CENDARI:old  url(r'^accounts/login/$', 'django.contrib.auth.views.login', { 'redirect_field_name': 'return_to' }),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', { 'redirect_field_name': 'return_to' }, name='user_login_view'),
    url(r'^accounts/logout/$', 'editorsnotes.main.views.auth.user_logout', name='user_logout_view'),
    url(r'^accounts/profile/$', 'editorsnotes.main.views.auth.user'),
    url(r'^accounts/profile/feedback/$', 'editorsnotes.main.views.auth.user_feedback', name='user_feedback_view'),
    url(r'^accounts/browserid/$', CustomBrowserIDVerify.as_view(), name='browserid_verify'),
    url(r'^user/(?P<username>[\w@\+\.\-]+)/$', 'editorsnotes.main.views.auth.user', name='user_view'),
)

# Base patterns
urlpatterns += patterns('editorsnotes.main.views.navigation',
#    url(r'^$', 'index', name='index_view'),
#    url(r'^about/$', 'about', name='about_view'),
#    url(r'^about/test/$', 'about_test'),
#    url(r'^search/$', 'search', name='search_view'),
    url(r'^version/$', 'get_version', name='get_version'),
)

# Admin patterns
urlpatterns += patterns('',
    url(r'^projects/(?P<project_slug>\w+)/', include('editorsnotes.admin.urls', namespace='admin', app_name='admin')),
    url(r'^projects/add/', 'editorsnotes.admin.views.projects.add_project', name='add_project_view'),
)

# Main model patterns
urlpatterns += patterns('',
    url(r'^', include('editorsnotes.main.urls')),
)

# API
urlpatterns += patterns('',
    url(r'^api/', include('editorsnotes.api.urls', namespace='api', app_name='api')),
    url(r'^api/metadata/topics/types/$', 'editorsnotes.api.views.topics.topic_types'),
)


urlpatterns += patterns('editorsnotes.djotero.views',
#    url(r'^document/upload/$', 'import_zotero', name='import_zotero_view'),
#    url(r'^document/upload/libraries/$', 'libraries', name='libraries_view'),
#    url(r'^document/upload/collections/$', 'collections', name='collections_view'),
#    url(r'^document/upload/items/$', 'items', name='items_view'),
#    url(r'^document/upload/continue/$', 'items_continue', name='items_continue_view'),
#    url(r'^document/upload/import/$', 'import_items', name='import_items_view'),
    url(r'^user/zotero_info$', 'update_zotero_info', name='update_zotero_info_view'),
    url(r'^api/metadata/documents/item_template/$', 'item_template', name='item_template_view'),
    url(r'^api/metadata/documents/item_types/$', 'item_types', name='item_types_view'),
    url(r'^api/metadata/documents/item_type_creators/$', 'item_type_creators', name='item_type_creators_view'),
    url(r'^api/document/archives/$', 'api_archives', name='api_archives_view'),
   # CENDARI:old url(r'^api/document/template/', 'zotero_template'),
   # CENDARI:old url(r'^api/document/blank/$', 'get_blank_item', name='get_blank_item_view'),
   # CENDARI:old url(r'^api/document/itemtypes/$', 'get_item_types'),
   # CENDARI:old url(r'^api/document/csl/$', 'zotero_json_to_csl', name='zotero_json_to_csl_view'),
   # CENDARI:old url(r'^api/document/archives/$', 'api_archives', name='api_archives_view'),
)
#urlpatterns += patterns('editorsnotes.refine.views',
#    url(r'^topics/clusters/$', 'show_topic_clusters', name='show_topic_clusters_view'),
#    url(r'^topics/merge/(?P<cluster_id>\d+)/$', 'merge_topic_cluster', name='merge_topic_cluster_view'),
#)

cendari/models.py
from django.db import models

from editorsnotes.main.models import Topic

class PlaceTopicModel(models.Model):
    topic = models.OneToOneField(Topic, related_name='location')
    lon = models.FloatField()
    lat = models.FloatField()

    @property
    def latlong(self):
        return [self.lat, self.lon]

cendari/templates/old/cendarisearch_old.html
{% extends "cendaribase.html" %}
{% load typogrify display %}
{% load staticfiles compress %}

%{% block title %}: Results for '{{ query }}'{% endblock %}

{% load render_search_results display typogrify %}

{% block css_nocompress %}
<link rel="stylesheet" href="{{ STATIC_URL }}style/facets.css" type="text/css" />
<style type="text/css">
  .highlighted {
    background: #faa732;
    padding: 2px;
  }
  .searchresult > a * {
    display: inline;
  }
  .searchresult {
    margin-bottom: .75em;
  }
  .searchresult .fragment {
    margin-bottom: 4px;
  }
  .searchresult .fragment * {
    display: inline;
  }
</style>
{% endblock %}

{% block js_nocompress %}
<script type="text/javascript" src="{{ STATIC_URL }}function/facets.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
      var facets = $('#results').facet({
        'fields': [
          {'key': 'model', 'label': 'Result type'}
        ],
        'itemSelector': '.searchresult'
      });
  });
</script>
{% endblock %}

{% block layout %}
<div id="searchresults" class="span-24 last">
{% if query %}
  {% if results %}
  <p id="message">Search results for <em>{{ query }}</em>:</p>
  <ol id="results" class="span-18 last">
    {% for result in results %}
      {{ result|render_search_result|safe }}
    {% endfor %}
  </ol>
  {% else %}
  <p id="message">No results for <em>{{ query }}</em>.</p> 
  {% endif %}
</div>
{% endif %}

{% endblock %}

cendari/templates/old/noteCendari.html
{% extends "centerCendari.html" %}
{% load set_var %}
{% load typogrify display note_sections staticfiles compress %}

{% block css %}
	<link rel="stylesheet" type="text/css" media="all" href="{% static "iipmooviewer/css/iip.css" %}" />
{% endblock %}

{% block init %}
	<meta name="note_id" id="note_id" content="{{ note.id }}" />
	<meta name="note_name" id="note_name" content="{{ note.title }}" />
{% endblock init %}

{% block model_fields %}
	<div class="form-menu-document" >
		<!-- <section id="note-details>" -->
		<ul class="tabs note">
			<li><!-- ENTITIES TAB -->
				<input type="radio" checked name="tabs" id="tab1">

				<label id='entitiesTab' for="tab1">
					<script > document.write("Entities (" + "{{ note.get_all_related_topics|length }}" + ")"); </script> 
				</label>

				<div id="tab-content1" class="tab-content  note animated fadeIn">
					<div class="form-entities" id="note-related-topics">
						{% if note %}
							{% for topic in note.get_all_related_topics %}
								<a href= {{ topic.get_absolute_url }}
								{% if 		topic.topic_node.type == "PER" %} class ="form-entities r_person"
								{% elif 	topic.topic_node.type == "ORG" %} class ="form-entities r_organization"
								{% elif 	topic.topic_node.type == "EVT" %} class ="form-entities r_event"
								{% elif 	topic.topic_node.type == "PLA" %} class ="form-entities r_place"
								{% elif 	topic.topic_node.type == "TAG" %} class ="form-entities r_thing"
								{% else 						%} class = "form-entities"
								{% endif %}
								> 
									{{ topic }} 
								</a>
							{% endfor %}
							{% if not note.get_all_related_topics|length > 0 %}
								<div>
									No Entities.
								</div>
								<div>
									select the Entity & right-click to add it
								</div>
							{% endif %}

						{% endif %}
						{% if not note.id > 0 %}
							<div>
								No Entities.
							</div>
							<div>
								Save this note to add your Entities
							</div>
						{% endif %}

					</div>
				</div>
			</li>

			<li><!-- STATUS TAB -->
				<input type="radio" name="tabs" id="tab2">
				<label for="tab2">Status {% if note.status == "0" %} (Closed) {% elif note.status == "2" %} (Hibernating)  {% else %} (Open) {% endif %}</label>
				<div id="tab-content2" class="tab-content note animated fadeIn">
					<div class="form-status" id="note-status">
						<select name="status">
							<option value="open" {% if note.status == 'open' %} selected="selected" {% endif %}><span class="note-status-closed">Closed</span></option>
							<option value="closed" {% if note.status == 'closed' %} selected="selected" {% endif %}><span class="note-status-closed">Closed</option>
							<option value="hibernate" {% if note.status == 'hibernating' %} selected="selected" {% endif %}><span class="note-status-hibernating" >Hibernating</span></option>
						</select>
					</div>
				</div>
			</li>

			<li><!-- AUTHORSHIP TAB (Project, Private, Licence, Author, Last updated ) -->
				<input type="radio" name="tabs" id="tab3">
				<label for="tab3">Authorship</label>
				<div id="tab-content3" class="tab-content note animated fadeIn">
					<div style="height:50px; overflow: auto;" >
						<dl id="note-authorship" >
						<!-- class="dl-horizontal">-->
						{% if note %}
							<dt>
								Project
							</dt>
							<dd>
								{{ note.project|as_link }}
							</dd>
							<dt>
								Private
							</dt>
							<dd>
								{% if note.is_private %}Yes{% else %}No{% endif %}
							</dd>
							<dt>
								License
							</dt>
							<dd>
								<a class="license-link" href="{{ license.url }}" title="{{ license }}"> {% for symbol in license.symbols %}<i class="license-symbol">{{ symbol }}</i>{% endfor %} </a>
							</dd>
							{% with authors=note.get_all_updaters %}
								<dt>
									Author{% if authors|length > 1 %}s{% endif %}
								</dt>
								<dd>
									{% for author in authors %}
										<li>
											{{ author|as_link }}
										</li>
									{% endfor %}
								</dd>
							{% endwith %}
							<br>
							<dt>
								Last updated
							</dt>
							<dd>
								{{ note.last_updated }} (<a href="#">view history</a>)
							</dd>
						{% endif %}
						</dl>
					</div>
				</div>
			</li>
		</ul>
		<!-- </section> -->




		<div class="stop-float"></div>
		<div style="height:5px"> &nbsp;</div>

		{% if note.id %}
			<form class="formCendari" id="noteCendari" action="{% url "api:api-notes-detail" project_slug=project.slug  pk=note.id %}" method="POST">  
			{% csrf_token %}
		{% else %}
			<form class="formCendari" id="noteCendari" action="{% url "api:api-notes-list" project_slug=project.slug %}" method="POST" >
			{% csrf_token %}
		{% endif %}
			<!-- <div class="form-main edit-section" > -->

			{% if not note.id %}
				<input type="hidden" name="related_topics" value="" /> 
				<input type="hidden" name="status" value="open" />
				<input type="hidden" name="is_private" value="false" />
			{% else %}
				<input type="hidden" name="related_topics" value="" />
				<input type="hidden" name="status" value="open" />
				<input type="hidden" name="is_private" value="{{note.is_private}}" />
				<input type="hidden" id = "model_id" name="id" value="{{note.id}}" />
			{% endif %}
			<div class="form-main edit-section" >
		
				<input  class="editorlabel" id="noteDescEditBut" type="button" value= {% if note.id > 0 %} "[ Read Only ]                --- click here for Edit mode" {% else %} "[ Editable ]                    --- click here for Read-Only mode" {% endif %} />
				<div data-error-target="note-title"></div>
				<!-- <label for="note-title">Note's title</label> -->
				<p>Note's title</p>
				<input type="text" id="note_title" name="title" style="height:30px;" value="{%if note%}{{note.title}}{%endif%}">
				<p>Notes's content</p>
				<div data-error-target="note-description"></div>
				<textarea id="note-description" type="text"  class="mceEditor" name="content"  >
				{% if note %} {{ note.content|as_html }} {% endif %}	
				</textarea>
				<!-- </section> -->

				<section id="note-sections">
					{% for section in sections %}{% include section|ns_template_name %}{% endfor %}
				</section>

				{% if note.id %}
					<button id="saveButton" style="visibility: hidden;" class="save-item" name="_method" value="PUT" >Save</button>
				{% else %}
					<button id="saveButton" style="visibility: hidden;" class="save-item"  method="POST" name="_method" value="POST">Save</button>
				{% endif %}
				<div id="statusMessages"></div>
			</div>

			
			
		</form>
	</div>
{% endblock model_fields %}

{% block functions %}

	<script>
		switchtabs(3, "note");
		$("#note-title").attr("placeholder", "Insert Note Title  . . . ");
		var isReadOnly = false, title = "New Note", id = document.getElementById("note_id").getAttribute("content");

		if (id > 0) {
			var name = document.getElementById("note_name").getAttribute("content");
			title = "Note " + id + ": " + name;
			isReadOnly = false;
		}

		var descriptionLabel = "Note Description ";
		var temp = document.getElementById("noteDescEditBut").getAttribute("value");
		document.getElementById("noteDescEditBut").value = descriptionLabel + temp;
		cendari.addInit(function() {
			cendari.createEditor(500, "note-description", isReadOnly, "noteDescEditBut", descriptionLabel);
			cendari.addTab(title);
			cendari.addWidgetToActiveTab("form", "noteform", "border");
		});
		{% if note %}
			// highlight associated entities in the paired vis panel
			var currentNoteEntities = "{{ note.get_all_related_topics_ids }}";
			window.postMessage({
				'messageType' : 'cendari_highlight',
				'targetWindowIds' : 'east',
				'entityIds' : currentNoteEntities,
				'highlightMode' : 1
			}, document.location.origin);
		{% endif %}

	</script>
{% endblock functions %}